# Generated by Django 5.0.4 on 2024-04-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_dadosmedico_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmedico',
            name='bairro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
