# Generated by Django 5.0.4 on 2024-04-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_dadosmedico_bairro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosmedico',
            old_name='celula_identidade_medica',
            new_name='cedula_identidade_medica',
        ),
    ]
